#!/bin/bash
if [ -z "$(command -v tmux)" ]; then
    echo "ERROR: tmux is not installed." 1>&2
    exit 1
fi

if [ "$(which tmux)" != "" ] && [ -z "$TMUX" ] && [ -t 1 ]; then

    # Default Session
    tmux has-session -t default 2>/dev/null || tmux new-session -d -s default

    tmux attach -t default

fi
